<a href="https://colab.research.google.com/github/Kushagragoel-code/data-science/blob/main/DAY-4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [6]:
a = np.array([1,3,4,5,6,'t',4])
print(a)

['1' '3' '4' '5' '6' 't' '4']


In [7]:
np_arr = np.array([3,3,3,3,'hello',False])
print(bool(np_arr[-1]))
a=False
print(a)

True
False


In [26]:
a=np.ones((9))
print(type(a))

<class 'numpy.ndarray'>


In [36]:
a = np.full(3,5,dtype=int)
print(a)

[5 5 5]


In [46]:
a=np.arange(5,10,2)
print(a)


[5 7 9]


In [43]:
a= np.linspace(2,2.6,6)
print(a)

[2.   2.12 2.24 2.36 2.48 2.6 ]


In [52]:
a = np.ones((2,3))
print(a.shape)
print(a.size)

(2, 3)
6


In [63]:
a = np.random.randint(3,10)
print(a)

6


In [78]:
a=np.random.choice((3,4,5))
print(a)

5


In [85]:
a= np.array([[3,4,5,6,],[4,5,3,2]])
b=np.array([[3,4,5,6],[4,4,2,3]])
print(a*2)
print(a*b)
print(a/b)

[[ 6  8 10 12]
 [ 8 10  6  4]]
[[ 9 16 25 36]
 [16 20  6  6]]
[[1.         1.         1.         1.        ]
 [1.         1.25       1.5        0.66666667]]


In [91]:
np.random.randint(2,4,2)
print(a)

[2, 3, 4, 4]


In [106]:
a = np.array([[4,5,2,3],[3,3,3,2]])
e = np.array([[4,5,2,3],[3,3,3,2]])
b = np.array([4,2,2,1])
c=np.array([4,2,2,1])
d = np.concatenate((a,e),axis=1)
print(d)
a=a.transpose()
print(a)


[[4 5 2 3 4 5 2 3]
 [3 3 3 2 3 3 3 2]]
[[4 3]
 [5 3]
 [2 3]
 [3 2]]


In [107]:
a = np.random.randint(3,12,6)
b= np.random.randint(3,12,6)
c=np.where(b>2,b,a)
print(c)

[8 6 8 5 9 8]


In [125]:
a = np.array([4,2,4,4,2,3])
b =np.sort(a)
print(b)
c=np.sum(a)
print(c)
print(np.min(a))
print(np.mean(a))
print(np.unique(a))
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
f = np.matmul(A, B)

print(f)

[2 2 3 4 4 4]
19
2
3.1666666666666665
[2 3 4]
[[19 22]
 [43 50]]


In [137]:
lst=[]

for i in range(7):


  t = (int(input()))
  lst.append(t)

a = np.array(lst)
print(np.sum(a))
print(np.min(a))
print(np.mean(a))


400
500
900
300
400
500
600
3600
300
514.2857142857143
