<a href="https://colab.research.google.com/github/Kushagragoel-code/data-science/blob/main/day-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
a = np.random.randint(-90,90,(5,5))
b = np.mean(a,axis=1)
c = np.mean(a,axis=0)


print("original matrix:\n" ,a)
print("mean row \n",b)
print("mean row \n",c)

d=a.copy()
d=np.where(d%2==0,-1,d)
print("\n")
print("replaced all even \n",d)
print("\n")
h = np.sort(a,axis=0)
i  = np.sort(a,axis=1)
print("sorted row \n",h)
print("\n")
print("sorted column \n",i)

u = np.sum(a,axis=0)
print("\n")
print("sum row \n",u)
o = np.sum(a,axis=1)
print("\n")
print("sum column \n",o)
count=0
for i in range(0,5):
  for j in range(0,5):
    if a[i][j]<0:
      count=count+1
print(count)


original matrix:
 [[-35  48 -48 -35 -52]
 [ -2  24 -60 -11  -2]
 [-30 -27  67  -3  51]
 [ 48 -49 -36 -55  48]
 [-14  49   7  88   6]]
mean row 
 [-24.4 -10.2  11.6  -8.8  27.2]
mean row 
 [ -6.6   9.  -14.   -3.2  10.2]


replaced all even 
 [[-35  -1  -1 -35  -1]
 [ -1  -1  -1 -11  -1]
 [ -1 -27  67  -3  51]
 [ -1 -49  -1 -55  -1]
 [ -1  49   7  -1  -1]]


sorted row 
 [[-35 -49 -60 -55 -52]
 [-30 -27 -48 -35  -2]
 [-14  24 -36 -11   6]
 [ -2  48   7  -3  48]
 [ 48  49  67  88  51]]


sorted column 
 [[-52 -48 -35 -35  48]
 [-60 -11  -2  -2  24]
 [-30 -27  -3  51  67]
 [-55 -49 -36  48  48]
 [-14   6   7  49  88]]


sum row 
 [-33  45 -70 -16  51]


sum column 
 [-122  -51   58  -44  136]
15


In [52]:
import numpy as np
a = np.random.randint(1,50,(5,5))
q = np.random.randint(1,50,(5,5))
w = a.copy()
print("stock \n",a)
print()
print("demand \n",q)
count =0
ans =0
for i in range(0,5):
  for j in range(0,5):

    w[i][j]-=q[i][j]
    if(w[i][j]<0):
      count-=w[i][j]
      ans=ans+1
print()
print("remaining stock \n",w)
s=np.where(w<0,0,w)
print()
print("replace value \n",s)
print()
print("total shortage \n",count)
print()
print("product with zero shortage \n",ans)
print(np.sort(w,axis=0))
print()
print(np.sort(w,axis=1))






stock 
 [[33 12 49 25 16]
 [12 29  8 24  9]
 [ 6 42 42  7 44]
 [ 9 40 16 21 26]
 [38 29 37 42 46]]

demand 
 [[24 34 16  7 48]
 [45 42 47  3  3]
 [ 3  1 44 48 46]
 [ 9  4 13 16 26]
 [41 47  2 35 15]]

remaining stock 
 [[  9 -22  33  18 -32]
 [-33 -13 -39  21   6]
 [  3  41  -2 -41  -2]
 [  0  36   3   5   0]
 [ -3 -18  35   7  31]]

replace value 
 [[ 9  0 33 18  0]
 [ 0  0  0 21  6]
 [ 3 41  0  0  0]
 [ 0 36  3  5  0]
 [ 0  0 35  7 31]]

total shortage 
 205

product with zero shortage 
 10
[[-33 -22 -39 -41 -32]
 [ -3 -18  -2   5  -2]
 [  0 -13   3   7   0]
 [  3  36  33  18   6]
 [  9  41  35  21  31]]

[[-32 -22   9  18  33]
 [-39 -33 -13   6  21]
 [-41  -2  -2   3  41]
 [  0   0   3   5  36]
 [-18  -3   7  31  35]]


In [63]:
import pandas as pd
file=pd.read_csv("./student_data.csv",sep=',')
print(file.tail(9))










      study_hours  attendance  sleep_hours  internet_usage  \
9991           10          93            7              11   
9992            5         100            9               2   
9993           10          86            9               9   
9994            4          53            7               8   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9991                      3              53       97.90           Placed  
9992                      9              62      100.00           Placed  
9993                     15              63      100.00           Placed  
9994                     10              71       85.02           Placed  
9995